package insurwave.blockwavebrokerAPI.constants;

/**
 * Defines the constants for the BrokerAPI node
 * 
 * @author saisree
 *
 */
public interface BrokerAPIConstants {

	String CONTRACT_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractJSONToEntity";
	String CONTRACT_SECTION_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractSectionJSONToEntity";
	String CONTRACT_SECTION_ASSET_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractSectionAssetJSONToEntity";
	String CONTRACT_SECTION_STEP2_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractSectionStep2AssetJSONToEntity";
	String CONTRACT_SUBSECTION_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractSubsectionJSONToEntity";
	String CONTRACT_SUBSECTION_INSURER_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractSubsectionInsurerJSONToEntity";
	String CONTRACT_SUBSECTION_PREMIUM_JSON_TO_ENTITY_TYPEMAP_NAME = "ContractSubsectionPremiumJSONToEntity";
	String SUBSECTION_PREMIUM_DEDUCTION_JSON_TO_ENTITY_TYPEMAP_NAME = "SubsectionPremiumDeductionJSONToEntity";
	String SUBSECTION_PREMIUM_TAX_JSON_TO_ENTITY_TYPEMAP_NAME = "SubsectionPremiumTaxJSONToEntity";
	String SUBSECTION_PREMIUM_DEDUCTIBLE_JSON_TO_ENTITY_TYPEMAP_NAME = "SubsectionPremiumDeductibleJSONToEntity";
	String PARTICIPANT_PUBLIC_ROLE_JSON_TO_ENTITY_TYPEMAP_NAME = "ParticipantPublicRoleJSONToEntity";
	String BLOCKWAVE_BROKERAPI_SPLUNK_LOGGER = "BlockWaveBrokerAPISplunkLogger";
	String UNKNOWN_ERROR = "Unknown Error occured:";
	String GROSS_PREMIUM = "GROSS_PREMIUM";
	String NET_PREMIUM_AFTER_DEDUCTIONS = "NET_PREMIUM_AFTER_DEDUCTIONS";
	String NET_PREMIUM_AFTER_BASE_TAX = "NET_PREMIUM_AFTER_BASE_TAX";
	String NET_PREMIUM_AFTER_BASE_TAX_DEDUCTIONS = "NET_PREMIUM_AFTER_BASE_TAX_DEDUCTIONS";
	String NET_PREMIUM_AFTER_COMPOUND_TAX = "NET_PREMIUM_AFTER_COMPOUND_TAX";
	String NET_PREMIUM_AFTER_DEDUCTIONS_AND_TAX = "NET_PREMIUM_AFTER_DEDUCTIONS_AND_TAX";
	String LINE_NET_PREMIUM_FOR_BUYER = "LINE_NET_PREMIUM_FOR_BUYER";
	String LINE_NET_PREMIUM_FOR_SELLERS = "LINE_NET_PREMIUM_FOR_SELLERS";
}
